# Versioning System
XTENDED_MAJOR_VERSION = XQ
XTENDED_RELEASE_VERSION = v8.0

XTENDED_BUILD_DATE := $(shell date +"%Y%m%d")

ifndef XTENDED_BUILD_TYPE
    XTENDED_BUILD_TYPE := XPLOITED
endif

TARGET_PRODUCT_SHORT := $(subst xtended_,,$(XTENDED_BUILD))

XTENDED_VERSION := Xtended-$(XTENDED_MAJOR_VERSION)-$(XTENDED_RELEASE_VERSION)-$(XTENDED_BUILD)-$(XTENDED_BUILD_TYPE)-$(XTENDED_BUILD_DATE)

XTENDED_MOD_VERSION := $(XTENDED_MAJOR_VERSION)-$(XTENDED_RELEASE_VERSION)

XTENDED_DISPLAY_VERSION := $(XTENDED_MOD_VERSION)-$(XTENDED_BUILD_TYPE)

XTENDED_FINGERPRINT := Xtended/$(XTENDED_MOD_VERSION)/$(TARGET_PRODUCT_SHORT)/$(XTENDED_BUILD_DATE)
